# Generated by Django 5.2.6 on 2025-09-15 19:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(choices=[('#007BFF', 'Azul'), ('#28A745', 'Verde'), ('#DC3545', 'Vermelho'), ('#FFC107', 'Amarelo'), ('#17A2B8', 'Ciano')], default='#007BFF', max_length=7)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
